import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Spotlight } from "../../components/motion-primitives/spotlight";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen dark`}
      >
        <Spotlight className="bg-blue-700 blur-2xl" size={64} />
        <main className="relative z-50">{children}</main>
        <Toaster richColors />
        <div className="absolute inset-0">
          <svg className="h-full w-full">
            <defs>
              <pattern
                id="grid-pattern"
                width="8"
                height="8"
                patternUnits="userSpaceOnUse"
              >
                <path
                  xmlns="http://www.w3.org/2000/svg"
                  d="M0 4H4M4 4V0M4 4H8M4 4V8"
                  stroke="currentColor"
                  strokeOpacity="0.3"
                  className="stroke-white dark:stroke-black"
                />
                <rect
                  x="3"
                  y="3"
                  width="2"
                  height="2"
                  fill="currentColor"
                  fillOpacity="0.25"
                  className="fill-white dark:fill-black"
                />
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#grid-pattern)" />
          </svg>
        </div>
      </body>
    </html>
  );
}
